version: "3.7"
services:
  database:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_USER_PASSWORD}
    expose: 
      - ${DB_PORT}
    networks: 
      - backend
    volumes:
      - /tmp:/volumes/host-volume
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  api:
    build: .
    ports: 
      - ${API_PORT}:${API_PORT}
    networks: 
      - backend
    depends_on:
      database:
        condition: service_healthy
networks:
  backend: {}